# Generated by Django 5.1.2 on 2024-10-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_manage', '0002_alter_billproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproduct',
            name='gst_applicable',
        ),
    ]
